import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
